baseURL: "https://ettoreciarcia.com/"
title: Ettore Ciarcia
paginate: 5
theme: PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

googleAnalytics: UA-123-45

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: Ettore Ciarcia
  description: "In this public space I'll talk about my Kubernetes and Cloud journey"
  keywords: [Blog, Portfolio, PaperMod]
  author: Ettore Ciarcia
  # author: ["Me", "You"] # multiple authors
  images: ["MemeK8s.jpeg"]
  DateFormat: "January 2, 2006"
  defaultTheme: auto # dark, light
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: false
  ShowWordCount: true
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false

  assets:
    # disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    favicon: "favicon.ico"
    favicon16x16: "favicon-16x16.png"
    favicon32x32: "favicon-32x32.png"
    apple_touch_icon: "apple-touch-icon.png"
    safari_pinned_tab: "<link / abs url>"

  label:
    text: "Home"
    # icon: /apple-touch-icon.png
    iconHeight: 35

  # profile-mode
  profileMode:
    enabled: true # needs to be explicitly set
    title: Ettore Ciarcia
    subtitle: > 
      Cloud Engineer @**[Epsilon](https://it.linkedin.com/company/epsilon_2)**
      
      
      Focused on Kubernetes, Terraform and AWS
    imageUrl: "android-chrome-512x512.png"
    imageWidth: 250
    imageHeight: 250
    imageTitle: me
    buttons:
      - name: Posts
        url: posts
      - name: Tags
        url: tags

  # home-info mode
  homeInfoParams:
    Title: "Hi there \U0001F44B"
    Content: >
        I'm Ettore, a young Cloud Engineer currently working at [Epsilon](https://it.linkedin.com/company/epsilon_2)! 

        - I'm focused on Kubernetes, Terraform and AWS. 
        
        - If you think you're better than me because I indent YAML be careful, I also indent HCL 🙂

  socialIcons:
    - name: twitter
      url: "https://twitter.com/ciarcia_ettore"
    - name: linkedin
      url: "https://www.linkedin.com/in/ettoreciarcia/"
    - name: github
      url: "https://github.com/ettoreciarcia"
    - name: curriculum
      url: "https://my-certification-ciarcia.s3.eu-west-1.amazonaws.com/EttoreCiarcia.pdf"



  analytics:
    google:
      SiteVerificationTag: "XYZabc"
    bing:
      SiteVerificationTag: "XYZabc"
    yandex:
      SiteVerificationTag: "XYZabc"

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: true # hide on single page

  editPost:
    URL: "https://github.com/ettoreciarcia/personal-website-hugo/tree/main/content/"
    Text: "Suggest Changes" # edit text
    appendFilePath: true # to append file path to Edit link

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]
menu:
  main:
    # - identifier: certifications
    #   name: certifications
    #   url: /certifications/
    #   weight: 4
    - identifier: Archive
      name: Archive
      url: archives
      weight: 1
    - identifier: Search
      name: Search
      url: search
      weight: 2
    - identifier: CV
      name: CV
      url: https://my-certification-ciarcia.s3.eu-west-1.amazonaws.com/EttoreCiarcia.pdf
      weight: 3
    - identifier: categories
      name: categories
      url: /categories/
      weight: 10
    - identifier: tags
      name: tags
      url: /tags/
      weight: 20
# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
pygmentsUseClasses: true
markup:
  highlight:
    noClasses: false
    # anchorLineNos: true
    # codeFences: true
    # guessSyntax: true
    # lineNos: true
    # style: monokai

#example site https://github.com/adityatelange/hugo-PaperMod/tree/exampleSite